M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu22.04.1} date 2025-10-13T12:48:48-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-13T12:48:48-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X54.0Y-54.0
X54.0Y-96.0
X146.0Y-54.0
X146.0Y-96.0
M30
